### ISSUE TITLE
Build on arm

### ISSUE THREAD

**Issue by chimneywindow** [surgitaix/sdclib#5]
Hello,
I have problems building the library on a raspberry pi (debian buster).
_make_ crashes at

libSDCLib_d.so: undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: ../../bin/libSDCLib_d.so: undefined reference to `__atomic_store_8'
/usr/bin/ld: ../../bin/libSDCLib_d.so: undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status

It will only be built if I add the following to the CMakeLists.txt.
_set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -latomic")_
Did I configure something wrong?

**Comment by FBaumeister** [comment]
Hello chimneywindow,
did you call the FindSDCLib.cmake script or how do you integrate the SDCLib into your project?

If via FindSDCLib.cmake, the SDCLib_LIBRARIES variable should already contain atomic (added it because of the ARM build issue).
See: https://github.com/surgitaix/sdclib/blob/4ffb97341fa322ee137c9015a9c907eff7fc1efb/cmake/Modules/FindSDCLib.cmake#L215-L216 .

One note on adding atomic to the LINK FLAGS:
I generally refrain from adding definitions or linker options to "global values" and try to stay on a "per target base" e.g. target_link_libraries(...).

Maybe I can help you better if you provide some more information on how you set up your project structure / Cmake file and how you build / include the SDCLib.

**Comment by chimneywindow** [comment]
Hello FBaumeister,
I tried to build the Examples.
I cloned the repository and installed the dependecies and tried to build with
`cmake .` and `make`

On x86 (Debian Buster) I could already build them with _in source_ and _out of source_ without problems so I was a little surprised about the error message on the raspberry pi.

**Comment by FBaumeister** [comment]
Hi,
yes, when I last tried to build the SDCLib on the Raspberry Pi 4 I got the same issue with atomic and was surprised too. I assume you are working on a Pi 4 too?

Thank you for reporting!
I will get a Pi and reproduce / work on a fix.

**Comment by FBaumeister** [comment]
You may want to pull the latest master version 4.3.8. Atomic is now added to SDCLib_DEPS_LIBRARIES and correctly added to the Examples. Confirmed bug and was able to build with the latest version on Raspberry Pi 4 with Raspbian buster, gcc 7.3.
Does that fix the issue for you too?

**Comment by chimneywindow** [comment]
The Raspberry Pi I use is a 3B+.
Now I can build it without problems, 
thank you for the fast fix!

**Comment by FBaumeister** [comment]
Ok, good to know that this happened on the Pi 3B+ too.
Thank you for reporting!
