### ISSUE TITLE
Setting Patient in WorkflowContextState is invalid?

### ISSUE THREAD

**Issue by Phips1989** [surgitaix/sdclib#9]
I have a "WorkflowContextStateHandler" with following code:

> 	WorkflowContextState getInitialState()
	{
		WorkflowContextState t_newState{getDescriptorHandle(), getDescriptorHandle()};
        	BaseDemographics baseDemographics;
        	PersonReference personReference;
        	baseDemographics.setGivenname(WORKFLOWCONTEXT_NAME);
        	personReference.setName(baseDemographics);
        	WorkflowDetail workflowDetail(personReference);
        	workflowDetail.setPatient(personReference);
        	t_newState.setWorkflowDetail(workflowDetail);
		return t_newState;
	}

When I compile and run it, it generates following runtime error:

> E 13:50:16.555 SDCLib.RAW.SCHEMA:
  Schema validation failed with error: :30:22 error: element 'Name' is not allowed for content model '(Extension?,Identification+,Name?)'
Offending message: 
<p1:MdibContainer xmlns:p1="http://standards.ieee.org/downloads/11073/11073-10207-2017/participant" MdibVersion="0" SequenceId="0">
  <p1:MdDescription/>
  <p1:MdState xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <p1:State DescriptorHandle="EnsembleContext" Handle="EnsembleContext" StateVersion="0" xsi:type="p1:EnsembleContextState">
      <p1:Category Code="Ensemble Category 1"/>
    </p1:State>
    <p1:State DescriptorHandle="LocationContext" Handle="LocationContext" StateVersion="0" xsi:type="p1:LocationContextState">
      <p1:LocationDetail PoC="Room 3"/>
    </p1:State>
    <p1:State DescriptorHandle="OperatorContext" Handle="OperatorContext" StateVersion="0" xsi:type="p1:OperatorContextState">
      <p1:OperatorDetails>
        <p1:Givenname>Hans Mueller</p1:Givenname>
      </p1:OperatorDetails>
    </p1:State>
    <p1:State DescriptorHandle="PatientContext" Handle="PatientContext" StateVersion="0" xsi:type="p1:PatientContextState">
      <p1:Category Code="Patient Category 1"/>
    </p1:State>
    <p1:State ActivationState="On" DescriptorHandle="SimpleMetric" StateVersion="0" xsi:type="p1:NumericMetricState">
      <p1:MetricValue DeterminationTime="0" Value="0">
        <p1:MetricQuality Validity="Vld"/>
      </p1:MetricValue>
    </p1:State>
    <p1:State DescriptorHandle="WorkflowContext" Handle="WorkflowContext" StateVersion="0" xsi:type="p1:WorkflowContextState">
      <p1:WorkflowDetail>
        <p1:Patient>
          <p1:Name>
            <p1:Givenname>Patient 0</p1:Givenname>
          </p1:Name>
        </p1:Patient>
      </p1:WorkflowDetail>
    </p1:State>
  </p1:MdState>
</p1:MdibContainer>

> F 13:50:16.555 SDCLib.SDC.PROVIDER:
  Fatal error, can't create MDIB - schema validation error! Offending MDIB: 
<p1:MdibContainer xmlns:p1="http://standards.ieee.org/downloads/11073/11073-10207-2017/participant" MdibVersion="0" SequenceId="0">
  <p1:MdDescription/>
  <p1:MdState xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <p1:State DescriptorHandle="EnsembleContext" Handle="EnsembleContext" StateVersion="0" xsi:type="p1:EnsembleContextState">
      <p1:Category Code="Ensemble Category 1"/>
    </p1:State>
    <p1:State DescriptorHandle="LocationContext" Handle="LocationContext" StateVersion="0" xsi:type="p1:LocationContextState">
      <p1:LocationDetail PoC="Room 3"/>
    </p1:State>
    <p1:State DescriptorHandle="OperatorContext" Handle="OperatorContext" StateVersion="0" xsi:type="p1:OperatorContextState">
      <p1:OperatorDetails>
        <p1:Givenname>Hans Mueller</p1:Givenname>
      </p1:OperatorDetails>
    </p1:State>
    <p1:State DescriptorHandle="PatientContext" Handle="PatientContext" StateVersion="0" xsi:type="p1:PatientContextState">
      <p1:Category Code="Patient Category 1"/>
    </p1:State>
    <p1:State ActivationState="On" DescriptorHandle="SimpleMetric" StateVersion="0" xsi:type="p1:NumericMetricState">
      <p1:MetricValue DeterminationTime="0" Value="0">
        <p1:MetricQuality Validity="Vld"/>
      </p1:MetricValue>
    </p1:State>
    <p1:State DescriptorHandle="WorkflowContext" Handle="WorkflowContext" StateVersion="0" xsi:type="p1:WorkflowContextState">
      <p1:WorkflowDetail>
        <p1:Patient>
          <p1:Name>
            <p1:Givenname>Patient 0</p1:Givenname>
          </p1:Name>
        </p1:Patient>
      </p1:WorkflowDetail>
    </p1:State>
  </p1:MdState>
</p1:MdibContainer>

**Comment by FBaumeister** [comment]
Hello Phips1989,
thank you for reporting.
If I'm correct the message "Schema validation failed with error: :30:22..." indicates that the parser (validation) complains about something with the 22nd character in line 30 of your MDIB.
It points to an Extension (?) you are using, but you did not provide the MdDescrition part. I assume that line 30 would be inside that area rather than inside MdState.
Or does the message show the whole MDIB?
Could you provide additional information?

**Comment by Phips1989** [comment]
Hello FBaumeister,

the message shows the whole MDIB (I think).

I uploaded the complete ProviderExample.
In fact I'm adding a "WorkflowHandler" via `addMdStateHandler` to a SDCProvider. 
[MinimalOperationProvider.txt](https://github.com/surgitaix/sdclib/files/4274132/MinimalOperationProvider.txt)

**Comment by FBaumeister** [comment]
Ah alright, now I see.
Thank you for providing the source code.
I investigated the issue with your source code and my first guess was wrong.
You have to add an InstanceIdentifier to the PersonReference because it has a minOccurence of 1 according to IEEE 11073-10207 (I'm sorry, got a little distracted due to the missing < > chars).
It would be something like:

```
#include <SDCLib/Data/SDC/MDIB/InstanceIdentifier.h>

personReference.addIdentification(InstanceIdentifier{}.setRoot("hello").setExtension("world"));
```

In addition to that:
Your SDCProvider is lacking an MdDescription. You only specify the MdState part.
This conflicts with Requirement R0023 of 11073-10207. Roughly speaking:
Every State in MdState must have a corresponding part in MdDescription (pairs of State/Descriptor), or Consumers will complain.

Thank you for reporting this. We will rework the API in a later version so that mandatory values will have to be specified by the user.
